name: FP1

on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 14 3 *'

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  scrape-latest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: |
            telFP1.py
            requirements.txt
            utils.py
          fetch-depth: 1

      - name: Get active event
        id: get-event
        run: |
          EVENT=$(grep -A1 "events = \[" telFP1.py | grep '"' | cut -d'"' -f2)
          echo "EVENT=$EVENT" >> $GITHUB_ENV

      - uses: actions/checkout@v3
        with:
          sparse-checkout: |
            telFP1.py
            requirements.txt
            utils.py
            ${{ env.EVENT }}/**
          fetch-depth: 1

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Create cache directory
        run: mkdir -p cache

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run Telemetry
        run: python telFP1.py run-all

      - name: Commit changes
        run: |
          git config --local user.name github-actions
          git config --local user.email "action@github.com"
          git pull origin main
          git add .
          if [[ "$(git status --porcelain)" != "" ]]; then
              git commit -m "Update data" -a
              git push -u origin main
          fi
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions
