name: R

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 16 3 *'

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  scrape-latest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: |
            telR.py
            requirements.txt
          fetch-depth: 1

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Create cache directory
        run: mkdir -p cache

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run Telemetry
        run: python telR.py run-all

      - name: Commit changes
        run: |
          git config --local user.name github-actions
          git config --local user.email "action@github.com"
          git pull origin main
          git add .
          if [[ "$(git status --porcelain)" != "" ]]; then
              git commit -m "Update data" -a
              git push -u origin main
          fi
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions
